name: basicflow

on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v4

      - name: Show all files
        run: |
          cd .github
          cd workflows
          ls -l
          ls -la
      - name: setup  nodejs version 
        uses: actions/setup-node@v4
      - name: checkout nodejs version 
        run : node -v 